export const DELETE_CONTACT = 'DELETE_CONTACT';

export const ADD_CONTACT_BEGIN = 'ADD_CONTACT_BEGIN';
export const ADD_CONTACT_SUCCESS = 'ADD_CONTACT_SUCCESS';
export const ADD_CONTACT_FAILURE = 'ADD_CONTACT_FAILURE';

export const GET_CONTACTS_BEGIN = 'GET_CONTACTS_BEGIN';
export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';
export const GET_CONTACTS_FAILURE = 'GET_CONTACTS_FAILURE';